---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - block:
        - name: Get key for repo
          become: true
          ansible.builtin.get_url:
            url: https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key
            dest: /usr/share/keyrings/clickhouse-keyring.asc
        - name: install repo
          become: true
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/usr/share/keyrings/clickhouse-keyring.asc] https://packages.clickhouse.com/deb stable main"
            state: present
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        name: 
          - clickhouse-client
          - clickhouse-server
        update_cache: yes
      notify: Start clickhouse service
    - name: Flush handlers
      meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0

#- name: Install vector
#  hosts: clickhouse
#  handlers:
#  tasks:
#    - name: Get vector
#      ansible.builtin.get_url: